version: "3.7"

volumes:
  zeebe0: {}
  zeebe1: {}
  zeebe2: {}
  zeebe_elasticsearch_data: {}

networks:
  zeebe_network:

services:
  zeebe0:
    image: camunda/zeebe:${ZEEBE_DEMO_VERSION}
    container_name: zeebe_broker_0
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_NODE_ID=0
    depends_on:
      - elasticsearch
    volumes:
        - zeebe0:/usr/local/zeebe/data
        - ./zeebe-hazelcast-exporter.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
        - ./application.yml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network

  
  monitor:
    container_name: zeebe_monitor
    restart: always
    image: camunda/zeebe-simple-monitor:${ZEEBE_MONITOR_VERSION}
    environment:
      - zeebe.client.broker.contactPoint=zeebe0:26500
      - zeebe.client.worker.hazelcast.connection=zeebe0:5701
    ports:
      - "8082:8082"
    depends_on:
      - zeebe0
    networks:
      - zeebe_network
  
  operate:
    container_name: operate
    image: camunda/operate:${ZEEBE_OPERATE_VERSION}
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
      - zeebe0
    volumes:
      - ./operate.application.yml:/usr/local/operate/config/application.yml
    networks:
      - zeebe_network
  
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - zeebe_elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - zeebe_network
  
  # kibana:
  #   container_name: kibana
  #   image: docker.elastic.co/kibana/kibana-oss:6.7.1
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - "5601:5601"
  #   networks:
  #     - zeebe_network

  # prometheus:
  #   image: prom/prometheus
  #   ports:
  #     - "9090:9090"
  #   links:
  #     - zeebe1
  #   volumes:
  #     - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  #   networks:
  #     - zeebe_network
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1'

  # grafana:
  #   image: grafana/grafana:latest
  #   environment:
  #       - GF_SECURITY_ADMIN_PASSWORD=pass
  #   depends_on:
  #       - prometheus
  #   ports:
  #       - "3000:3000"
  #   volumes:
  #       - ./grafana/provisioning/:/etc/grafana/provisioning/
  #       - ./grafana/conf/grafana.ini:/etc/grafana/grafana.ini
  #   networks:
  #     - zeebe_network  
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1'